USE AB_INFOBANC
GO


CREATE OR ALTER PROCEDURE BAAS_LISTAR_ESTADOS (@UF VARCHAR(2) = NULL) AS 
BEGIN

	SELECT		CODESTADO AS Sigla,
				DESCRICAO AS Estado
	FROM		ESTADOS
	WHERE		(@UF IS NULL OR CODESTADO = @UF)	
	ORDER BY	CODESTADO

END