USE AB_INFOBANC
GO

CREATE OR ALTER PROCEDURE BAAS_INFOBANK_LISTAR_COLIGADAS (@CODCOLIGADA VARCHAR(10) = NULL) AS

BEGIN

		SELECT		CODCOLIGADA AS Codigo,
					NOME AS Coligada,
					CGC AS Cnpj,
					TIPOCOLIGADA AS Tipo,
					CODBANCO AS CodigoBanco,
					Endereco,
					Complemento,
					Bairro,
					Cidade,
					Uf,
					Cep,
					Telefone					
		FROM		COLIGADAS
		WHERE		(@CODCOLIGADA IS NULL OR CODCOLIGADA = @CODCOLIGADA)
		ORDER BY	CAST(CODCOLIGADA AS BIGINT) ASC

END