USE AB_INFOBANC
GO


CREATE OR ALTER PROCEDURE BAAS_INFOBANK_LISTAR_AGENCIAS_BANCO (@CODBANCO VARCHAR(5)) AS
BEGIN

	SELECT		CODAGENCIA AS CodigoAgencia,
				Nome AS Agencia,
				ISNULL(CGC, '') AS CnpjAgencia,
				INDATIVA AS Ativa,
				Cidade,
				Uf,
				Endereco
	FROM		BANCO_AGENCIAS
	WHERE		CAST(CODBANCO AS INT) = CAST(@CODBANCO AS INT)
	ORDER BY	CAST(CODAGENCIA AS BIGINT) ASC

END

