USE AB_INFOBANC
GO


CREATE OR ALTER PROCEDURE BAAS_INFOBANK_LISTAR_BANCOS (@CODBANCO VARCHAR(5) = NULL, @CODISPB VARCHAR(10) = NULL) AS
BEGIN


	SELECT		CODBANCO AS Codigo,
				Nome,
				ISNULL(CGC, '') AS Cnpj,
				INDATIVOSTR AS AtivoSTR
	FROM		BANCOS
	WHERE		(@CODBANCO IS NULL OR CODBANCO = @CODBANCO)
	AND			(@CODISPB IS NULL OR CODISPB = @CODISPB)
	ORDER BY	CAST(CODBANCO AS INT) ASC

END

