USE AB_PAGAMENTO_INSTANTANEO
GO

CREATE OR ALTER PROCEDURE BAAS_PIX_LISTAR_PARTICIPANTES (@ISPB VARCHAR(8) = NULL) AS

BEGIN
	
	IF OBJECT_ID('tempdb..#Dados') IS NOT NULL
    DROP TABLE #Dados

	SELECT		CODISPB AS Ispb,
				TIPOPARTICIPANTE TipoParticipante,
				SITUACAOPARTICIPANTE AS Situacao,
				MODALIDADE_PARTICIPACAO AS Modalidade,
				RTRIM(LTRIM(ISNULL(ISNULL(NOMERESUMIDO, NOME), ''))) AS Participante
	into		#Dados
	FROM		PARTICIPANTE_PIX
	WHERE		(@ISPB IS NULL OR CODISPB = @ISPB)

	UPDATE	D
	SET		D.Participante = B.NOME
	FROM	#Dados D INNER JOIN AB_INFOBANC.dbo.BANCOS B
				ON D.Ispb = B.CODISPB
	WHERE	LEN(D.Participante) = 0


	SELECT		*
	FROM		#Dados
	ORDER BY	CAST(Ispb AS INT)

END