USE AGENCIAW
GO


CREATE OR ALTER PROCEDURE BAAS_LISTAR_HISTORICOS_CONTA (@CODHIST VARCHAR(10) = NULL) AS

BEGIN

	SELECT		CODHIST AS Codigo,
				TIPOHIST AS Tipo,
				DESCRICAO AS Historico,
				Natureza,
				Categoria,
				Status
	FROM		HISTORICO_CC
	WHERE		(@CODHIST IS NULL OR CODHIST = @CODHIST)
	ORDER BY	CODHIST

END

