USE AGENCIAW
GO

CREATE OR ALTER PROCEDURE BAAS_SALDO_CONTA (@CODCOLIGADA VARCHAR(5), @CODAGENCIA VARCHAR(5), @NROCONTA VARCHAR(15)) AS
BEGIN

	IF OBJECT_ID('tempdb..#Dados') IS NOT NULL
		DROP TABLE #Dados

	DECLARE @MOV_PRO_CRE	DM_MONEY,
			@MOV_PRO_DEB	DM_MONEY,
			@LIMITE			DM_MONEY


	/* MOVTOS PROVISORIOS */
	EXEC P_MONTANTE_MOVTO_PROVISORIO_AUTK_24x7
				@CODCOLIGADA,
				@CODAGENCIA,
                @NROCONTA,
                @MOV_PRO_CRE OUTPUT,
                @MOV_PRO_DEB OUTPUT 

	
	IF @MOV_PRO_CRE IS NULL 
			SELECT @MOV_PRO_CRE = 0.00

	IF @MOV_PRO_DEB IS NULL
			SELECT @MOV_PRO_DEB = 0.00


	EXEC 	SP_CALCULA_LIMITE 	
				@CODCOLIGADA,
				@CODAGENCIA,
				@NROCONTA,
				@LIMITE		OUTPUT	

	SELECT	A.NROCONTA AS Conta,
			B.NOME AS Titular,
			A.SDODIA0 AS SaldoD0,
			@LIMITE + ISNULL(A.LIMITEADC,0) AS Limite,
			(ISNULL(A.PROVCPMFANT,0) + ISNULL(A.PROVCPMFATU,0)) - (ISNULL(A.DEVCPMFANT,0) + ISNULL(A.DEVCPMFATU,0)) AS Cpmf,      	
			A.SDOCIP AS SaldoBloqueadoCip,
			A.SDOBLOQ0 AS SaldoBloqueado,
			A.VALORBLOQ AS ValorBloqueado,						
			((ISNULL(A.PROVCPMFANT,0) + ISNULL(A.PROVCPMFATU,0)) - (ISNULL(A.DEVCPMFANT,0)  + ISNULL(A.DEVCPMFATU,0)))  +
			(@MOV_PRO_CRE - @MOV_PRO_DEB) AS SaldoProvisorio,
			CAST(0 AS NUMERIC(21,2)) AS SaldoDisponivel
  FROM		CONTA A INNER JOIN TITULARES C 
				ON A.NROCONTA = C.NROCONTA 
				AND C.TITULARIDADE = '01'
				AND A.CODCOLIGADA = C.CODCOLIGADA
				AND A.CODAGENCIA = C.CODAGENCIA
			INNER JOIN AB_INFOBANC.dbo.CLIENTES B
				ON C.CODCLIENTE = B.CODCLIENTE   
			        
  
END